# Generated by Django 5.0.7 on 2024-08-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0021_auto_20240726_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencename',
            name='firstYear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conferencename',
            name='lastYear',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
